(require :asdf)
(asdf:load-system :lightfast)
(lightfast:load-library)
(lightfast:enable-thread-wakeups)
(let* ((window (lightfast:make-window :width 200 :height 100 :label "awake"))
       (woken nil))
  (lightfast:show window)
  (sb-thread:make-thread (lambda () (sleep 0.3) (setf woken t) (lightfast:awake)))
  ;; Without AWAKE this wait would run the full five seconds.
  (let ((start (get-internal-real-time)))
    (lightfast:wait 5.0)
    (loop until woken do (lightfast:wait 5.0))
    (let ((elapsed (/ (- (get-internal-real-time) start) internal-time-units-per-second)))
      (assert (< elapsed 2.0) () "wait was not woken early: ~,2F s" elapsed)
      (format t "~&awake smoke passed in ~,2F s~%" elapsed)))
  (lightfast:destroy window))
