(require :asdf)
(asdf:load-system :lightfast)
(lightfast:load-library)
(let* ((names (lightfast:system-font-names))
       (first-name (first (first names)))
       (font (lightfast:load-font first-name))
       (again (lightfast:load-font first-name)))
  (assert (plusp (length names)) () "no system fonts enumerated")
  (assert (= font again) () "loading the same face twice gave two numbers")
  (assert (string= (lightfast:font-name font) first-name))
  (multiple-value-bind (width height descent)
      (lightfast:measure-text "Lightfast" :font font :size 16)
    (assert (plusp width))
    (assert (plusp height))
    (assert (<= 0 descent height))
    (multiple-value-bind (wider) (lightfast:measure-text "Lightfast Lightfast" :font font :size 16)
      (assert (> wider width))))
  (format t "~&Lightfast font smoke passed with ~D faces; first is ~S.~%" (length names) first-name))
