(require :asdf)
(asdf:load-system :lightfast)
(lightfast:load-library)
(lightfast:apply-flat-theme :background '(255 254 250))
(let* ((window (lightfast:make-window :width 400 :height 300 :label "text smoke"))
       (display (lightfast:make-text-display :parent window :x 10 :y 10 :width 380 :height 280)))
  (lightfast:text-set-styles display
                             (list (list :font 0 :size 14 :color '(0 0 0))
                                   (list :font 1 :size 14 :color '(3 117 85)
                                         :attributes lightfast:+text-attribute-underline+)))
  (lightfast:text-append-styled display '(("Příliš žluťoučký kůň" . 0) (" úpěl" . 1)))
  (assert (= (lightfast:text-length display)
             (lightfast:string-byte-length "Příliš žluťoučký kůň úpěl")))
  (assert (string= "Příliš" (lightfast:text-range display 0 (lightfast:string-byte-length "Příliš"))))
  (lightfast:text-append-styled display (list (cons (format nil "~%second line") 0)))
  (assert (= 2 (lightfast:text-line-of-position display (lightfast:text-length display))))
  (lightfast:text-replace-styled display 0 (lightfast:string-byte-length "Příliš") '(("Very" . 1)))
  (assert (string= "Very" (lightfast:text-range display 0 4)))
  (assert (string= "" (lightfast:text-selection display)))
  (lightfast:show window)
  (loop repeat 10 do (lightfast:wait 0.02))
  (assert (integerp (lightfast:text-position-at display 20 20)))
  (assert (null (lightfast:text-position-at display -50 -50)))
  (lightfast:text-scroll-to-end display)
  (assert (= 1 (lightfast:text-top-line display)))
  (let ((path (format nil "/tmp/lightfast-capture-~D.ppm" (sb-posix:getpid))))
    (lightfast:capture-window window path)
    (with-open-file (stream path :element-type '(unsigned-byte 8))
      (assert (> (file-length stream) (* 400 300 3)) () "capture too small"))
    (delete-file path))
  (lightfast:destroy window))
(format t "~&Lightfast text smoke passed.~%")
