(require :asdf)
(asdf:load-system :lightfast)
(lightfast:load-library)
(let* ((names (lightfast:system-font-names))
       (first-name (first (first names)))
       (font (lightfast:load-font first-name))
       (again (lightfast:load-font first-name)))
  (assert (plusp (length names)) () "no system fonts enumerated")
  (assert (= font again) () "loading the same face twice gave two numbers")
  (assert (string= (lightfast:font-name font) first-name))
  (multiple-value-bind (width height descent)
      (lightfast:measure-text "Lightfast" :font font :size 16)
    (assert (plusp width))
    (assert (plusp height))
    (assert (<= 0 descent height))
    (multiple-value-bind (wider) (lightfast:measure-text "Lightfast Lightfast" :font font :size 16)
      (assert (> wider width))))
  ;; A tall label and a short button in one row meet on their baselines after
  ;; ALIGN-BASELINES, whatever their heights and sizes.
  (lightfast:apply-flat-theme)
  (let* ((window (lightfast:make-window :width 400 :height 100 :label "baselines"))
         (title (lightfast:make-label :parent window :x 10 :y 10 :width 150 :height 40 :label "Title"))
         (button (lightfast:make-button :parent window :x 170 :y 10 :width 100 :height 30 :label "Button")))
    (lightfast:set-label-size title 28)
    (lightfast:set-label-size button 14)
    (lightfast:align-baselines (list title button))
    (lightfast:refresh-geometry title)
    (lightfast:refresh-geometry button)
    (assert (= (+ (lightfast:widget-y title) (lightfast:widget-baseline title))
               (+ (lightfast:widget-y button) (lightfast:widget-baseline button)))
            () "baselines differ after alignment")
    (lightfast:destroy window))
  (format t "~&Lightfast font smoke passed with ~D faces; first is ~S.~%" (length names) first-name))
