(require :asdf)
(asdf:load-system :lightfast)
(lightfast:load-library)
(let* ((outer   (lightfast:make-rect :x 10 :y 20 :width 101 :height 30))
       (inner   (lightfast:rect-inset outer :horizontal 5 :vertical 2))
       (columns (lightfast:rect-columns outer 2 :gap 1)))
  (assert (= 15 (lightfast:rect-x inner)))
  (assert (= 22 (lightfast:rect-y inner)))
  (assert (= 91 (lightfast:rect-width inner)))
  (assert (= 26 (lightfast:rect-height inner)))
  (assert (= 2 (length columns)))
  (assert (= 50 (lightfast:rect-width (first columns))))
  (assert (= 50 (lightfast:rect-width (second columns))))
  (assert (= 61 (lightfast:rect-x (second columns)))))
(format t "~&Lightfast load smoke passed.~%")
